/* AUTOGENERATED by arrow-components-builder. DO NOT EDIT.
   Source: Figma 470rar5EfRm4n14vHMXbpc / page-title view=mobile (1073:787) и back-sheet (1073:2928), synced 2026-10-10.
   Page title — «Назад» открывает шторку «Вернуться».

   Ссылка «Назад» в разметке ведёт на ближайший раздел выше: без скрипта она просто
   переходит туда. Скрипт превращает её в кнопку окна — role="button", Space нажимает,
   клик открывает <dialog> через showModal(). Клик с модификатором (новая вкладка) и
   средней кнопкой остаётся переходом.
   Закрытие: крестик [data-ptitle-close], Esc (платформа), клик по подложке (нажатие и
   отпускание снаружи окна). Прокрутка страницы под окном блокируется на <html> —
   CSS блока в @scope до него не достаёт.

   Подключить один раз; блок, вставленный в DOM позже, подхватывает MutationObserver.
   Для ручного вызова — window.awdsPageTitleInit(root). */
(function () {
  function lock(on) { document.documentElement.style.overflow = on ? 'hidden' : ''; }

  function init(root) {
    if (root.hasAttribute('data-ptitle-ready')) return;
    var back = root.querySelector('[data-ptitle-back]');
    var sheet = root.querySelector('[data-ptitle-sheet]');
    if (!back || !sheet || typeof sheet.showModal !== 'function') return;
    root.setAttribute('data-ptitle-ready', '');

    back.setAttribute('role', 'button');
    back.setAttribute('aria-haspopup', 'dialog');
    function open() { lock(true); sheet.showModal(); }
    back.addEventListener('click', function (e) {
      if (e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
      e.preventDefault();
      open();
    });
    back.addEventListener('keydown', function (e) {
      if (e.key === ' ') { e.preventDefault(); open(); }
    });

    sheet.addEventListener('close', function () { lock(false); back.focus(); });
    Array.prototype.forEach.call(sheet.querySelectorAll('[data-ptitle-close]'), function (b) {
      b.addEventListener('click', function () { sheet.close(); });
    });
    // Подложка: цель клика — сам <dialog>, точка — вне его коробки. Нажатие внутри и
    // отпускание снаружи (выделение текста) окно не закрывает.
    var downOutside = false;
    function outside(e) {
      if (e.target !== sheet) return false;
      var r = sheet.getBoundingClientRect();
      return e.clientX < r.left || e.clientX > r.right || e.clientY < r.top || e.clientY > r.bottom;
    }
    sheet.addEventListener('pointerdown', function (e) { downOutside = outside(e); });
    sheet.addEventListener('click', function (e) { if (downOutside && outside(e)) sheet.close(); downOutside = false; });
  }

  function initAll(scope) {
    Array.prototype.forEach.call((scope || document).querySelectorAll('.ptitle:not([data-ptitle-ready])'), init);
  }
  window.awdsPageTitleInit = function (root) { if (root) init(root); else initAll(); };

  function start() {
    initAll();
    if (window.MutationObserver) {
      new MutationObserver(function () { initAll(); }).observe(document.body, { childList: true, subtree: true });
    }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start);
  else start();
})();
