/* AUTOGENERATED by arrow-components-builder. DO NOT EDIT.
   Source: Figma UCYhMA1JeNUNuVGsxUEne7 / node 2093:3494 (Range), synced 2026-06-18.
   Range — авто-инициализация: синхронит value нативных .range__input в CSS-переменные
   --range-from / --range-to (доли 0–1).
   Single — один input (→ --range-to).
   Double — два input (inputs[0]=from, inputs[1]=to) с ОГРАНИЧЕНИЕМ перемещения ручек
   (как doka.guide/recipes/input-range-style — «ограничение перемещения ручек»):
     • ручки не пересекаются: from зажимается ≤ to, to зажимается ≥ from;
     • z-index: когда верхняя ручка (to) в самом минимуме — поднимаем её поверх нижней,
       чтобы её можно было ухватить и потянуть вправо (иначе её перекрывает from).
   Подключить один раз; для динамически добавленных вызывать awdsRangeInit(root). */
(function () {
  function val(input) { return parseFloat(input.value); }
  function minOf(input) { var m = parseFloat(input.min); return isNaN(m) ? 0 : m; }
  function maxOf(input) { var m = parseFloat(input.max); return isNaN(m) ? 100 : m; }
  function frac(input) { var lo = minOf(input), hi = maxOf(input), span = (hi - lo) || 1; return (val(input) - lo) / span; }

  function setVars(range, fromI, toI) {
    if (toI) {
      range.style.setProperty('--range-from', frac(fromI));
      range.style.setProperty('--range-to', frac(toI));
    } else {
      range.style.setProperty('--range-to', frac(fromI));
    }
  }

  /* Нижняя ручка не заходит за верхнюю. */
  function controlFrom(range, fromI, toI) {
    if (val(fromI) > val(toI)) fromI.value = toI.value;
    setVars(range, fromI, toI);
  }

  /* Верхняя ручка не заходит за нижнюю + доступность на краю. */
  function controlTo(range, fromI, toI) {
    if (val(toI) < val(fromI)) toI.value = fromI.value;
    // когда to у самого минимума — поднимаем её поверх from (иначе не ухватить)
    toI.style.zIndex = (val(toI) <= minOf(toI)) ? '4' : '';
    setVars(range, fromI, toI);
  }

  function init(root) {
    var ranges = (root || document).querySelectorAll('.range');
    for (var i = 0; i < ranges.length; i++) {
      var range = ranges[i];
      if (range.dataset.awdsRangeInit) continue;
      range.dataset.awdsRangeInit = '1';
      var inputs = range.querySelectorAll('.range__input');
      if (range.classList.contains('range--double') && inputs.length >= 2) {
        (function (r, f, t) {
          f.style.zIndex = '3';   // нижняя ручка по умолчанию сверху → её всегда можно ухватить
          f.addEventListener('input', function () { controlFrom(r, f, t); });
          t.addEventListener('input', function () { controlTo(r, f, t); });
          controlTo(r, f, t);     // выставить z-index/доли по стартовым значениям
        })(range, inputs[0], inputs[1]);
      } else if (inputs[0]) {
        (function (r, inp) {
          inp.addEventListener('input', function () { setVars(r, inp, null); });
        })(range, inputs[0]);
        setVars(range, inputs[0], null);
      }
    }
  }

  if (document.readyState !== 'loading') init();
  else document.addEventListener('DOMContentLoaded', function () { init(); });

  window.awdsRangeInit = init;
})();
